flowchart TB
    start(["スタート"])
    UserInteraction[/"ユーザーとの対話開始"/]
    StartMainProcess["メイン処理スタート"]
    LoadAppConfig["AppConfigを読み取る"]
    CheckInputs/OutputsFromConfig["AppConfigのインプットとアウトプット確認"]
    LoadInputFiles["インプットデータを読み取る"]
    LoadMasterFile["モデルマスタを読み取る"]
    GetTranslations["日英翻訳を取得"]
    Check/ChangeStrings["文字列操作"]
    CompareWithPrevious["AS400累計と比べ"]
    OutputFiles["ファイル複数出力"]
    OutputFinalMessage["処理完了メッセージを表示"]
    End(["終了"])

    start
    --> UserInteraction
    --> StartMainProcess
    --> LoadAppConfig
    --> CheckInputs/OutputsFromConfig
    --> LoadInputFiles
    --> LoadMasterFile
    --> GetTranslations
    --> Check/ChangeStrings
    --> CompareWithPrevious
    --> OutputFiles
    --> OutputFinalMessage
    --> End
    
